"""
Shared KISS protocol constants.

Used by both KissSerialWrapper and KissTcpWrapper.
"""

KISS_FEND = 0xC0
KISS_FESC = 0xDB
KISS_TFEND = 0xDC
KISS_TFESC = 0xDD

_KISS_FEND_B = bytes([KISS_FEND])
_KISS_FESC_B = bytes([KISS_FESC])

KISS_MASK_PORT = 0xF0
KISS_MASK_CMD = 0x0F

KISS_CMD_DATA = 0x00
KISS_CMD_TXDELAY = 0x01
KISS_CMD_PERSIST = 0x02
KISS_CMD_SLOTTIME = 0x03
KISS_CMD_TXTAIL = 0x04
KISS_CMD_FULLDUP = 0x05
KISS_CMD_VENDOR = 0x06
KISS_CMD_RETURN = 0xFF

MAX_FRAME_SIZE = 512
RX_BUFFER_SIZE = 1024
TX_BUFFER_SIZE = 1024

DEFAULT_TIMEOUT = 1.0
